name: rhymer
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  # assets:
  #   - assets/
